SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS sheila_stephen_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE sheila_stephen_test;

DROP TABLE IF EXISTS clients;
CREATE TABLE clients (
  clientId int(11) NOT NULL,
  clientName varchar(255) NOT NULL,
  stylistId int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS stylists;
CREATE TABLE stylists (
  stylistId int(11) NOT NULL,
  stylistName varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE clients
  ADD PRIMARY KEY (clientId);

ALTER TABLE stylists
  ADD PRIMARY KEY (stylistId);


ALTER TABLE clients
  MODIFY clientId int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=162;

ALTER TABLE stylists
  MODIFY stylistId int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=196;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
